### ISSUE TITLE
Can you provide more convenient examples

### ISSUE THREAD

**Issue by burakakca** [hnaderi/edomata#108]
I look the existing example in the repo but I didn't quite understand. Also Tutorial documentation It's okay but I want to run these tutorial examples. [For example](https://edomata.ir/tutorials/1-1_eventsourcing.html)

**Comment by hnaderi** [comment]
I'll soon create an example project from tutorial, is that OK?
Are there any other thing that might help?

**Comment by burakakca** [comment]
- scalajs
- more examples for eventsorcing and cqrs

**Comment by hnaderi** [comment]
I just created an example here https://github.com/hnaderi/edomata-example
Take a look and feel free to start a discussion if you had any problems.
About ZIO, I had created an example for ZIO docs, but I'm not sure if that's a repo or not, so I'll add them too, in few days maybe.

**Comment by burakakca** [comment]
Thanks, I'm looking at the example, I would like to see examples of scaljs and zio. I especially want to see how I can use edomata in scalajs

**Comment by hnaderi** [comment]
Edomata can be used in ScalaJS on the server side using the same exact code that runs on JVM (if you don't have other dependencies that prevent that).
To use it on the client side, you can use the same exact services (which is very handy for demonstration and/or dev usage, as you are running your server logic on browser). However, running a complete Edomata application on the browser (while possible and easy to do) is an uncommon or rather eccentric task IMO, as the main usage of such systems is on the server side.
Could you please elaborate on what do you mean by scalajs example? so I can add a few helpful examples.

**Comment by burakakca** [comment]
It is nothing special just an example. Also, I try to migrate cats effect to ZIO but I didn't succeed. Can you share the ZIO example

**Comment by burakakca** [comment]
How can I listen to the events that I run in Edomata. It comes as a date, but for example, how can I catch this notification and take action when the deposit is updated. Also is it possible for me to stream this on zio

**Comment by hnaderi** [comment]
Listening to events is done using the storage backend,
see here for example https://github.com/hnaderi/edomata-example/blob/05609b7f54388dae89b9a925eea21b794db9fd39/core/src/main/scala/dev/hnaderi/example/Main.scala#L63

Also there is a helper named `OutboxConsumer` that lets you handle events as they come and run a side effect.

**Comment by hnaderi** [comment]
On the ZIO example, I'll update in a few days; 
Basically it is nothing but ZIO interop on this example, and all the features are supported as edomata doesn't care about the effect type is written in a tagless style.

**Comment by hnaderi** [comment]
So, I just updated https://github.com/hnaderi/edomata-example 
And it also includes `ZIO`.
please take a look and let's have a discussion if there are anything missing or needs more examples.
@burakakca

**Comment by BNationsDEV** [comment]
Hi @hnaderi,
Thank you for your support! I think that integrating Edomata Event Sourcing model with a Bi-temporal Database like "XTDB". What do you think about it? There is no open-source FSM library that support bi-temporal sourcing and queries. Edomata could be best option to do this. Please help us with examples to develop Edomata with XTDB queries!!

**Comment by BNationsDEV** [comment]
https://docs.xtdb.com/concepts/trucks-tubes-truth/

**Comment by hnaderi** [comment]
> Hi @hnaderi, Thank you for your support! I think about integrating Edomata Event Sourcing model with a Bi-temporal Database like "XTDB". What do you think about it? There is no open-source FSM library that support bi-temporal sourcing and queries. Edomata could be best option to do this. Please help us with examples to develop Edomata with XTDB queries!!

Hi @BNationsDEV 
Thank you for your interest in Edomata,
That would be interesting! we can have a discussion about it, I'll open a new issue to talk about it
